services:
  - type: web
    name: ambp
    env: python
    buildCommand: pip install --no-cache-dir --disable-pip-version-check -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT --workers 1 --access-log false
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PIP_NO_CACHE_DIR
        value: 1
      - key: PYTHONUNBUFFERED
        value: 1
      - key: PYTHONDONTWRITEBYTECODE
        value: 1
    healthCheckPath: /health
    autoDeploy: false
    region: singapore