services:
  # Web service
  - type: web
    name: ambp
    env: docker
    image: hafidzduddin/ambp:latest
    autoDeploy: true
    healthCheckPath: /health
    startCommand: "uvicorn app.main:app --host 0.0.0.0 --port $PORT --workers 1"
    scaling:
      minInstances: 1
      maxInstances: 1
      targetMemoryPercent: 80
      targetCPUPercent: 80
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        sync: false  # Use Supabase Legacy JWT Secret
      - key: GOOGLE_SHEET_ID
        sync: false
      - key: GOOGLE_CREDS_JSON
        sync: false
      - key: APP_URL
        fromService:
          name: ambp
          type: web
          property: url
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: SUPABASE_SERVICE_KEY
        sync: false