name: Cleanup

on:
  schedule:
    - cron: '0 17 * * *' # Setiap jam 00:00 WIB
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install GitHub CLI
        run: |
          sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-key C99B11DEB97541F0
          sudo apt-add-repository https://cli.github.com/packages
          sudo apt update
          sudo apt install gh -y

      - name: Install gh-actions-cache extension
        run: gh extension install actions/gh-actions-cache

      - name: Delete all GitHub Actions caches
        run: gh actions-cache delete --all --confirm

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Delete Docker Hub tags except "latest"
        env:
          REPO: ${{ secrets.DOCKERHUB_USERNAME }}/your-repo-name
        run: |
          echo "Fetching tags from $REPO..."
          tags=$(curl -s "https://hub.docker.com/v2/repositories/$REPO/tags?page_size=100" | jq -r '.results[].name')
          for tag in $tags; do
            if [ "$tag" != "latest" ]; then
              echo "Deleting Docker tag: $tag"
              curl -X DELETE \
                -u "${{ secrets.DOCKERHUB_USERNAME }}:${{ secrets.DOCKERHUB_TOKEN }}" \
                "https://hub.docker.com/v2/repositories/$REPO/tags/$tag/"
            fi
          done
