name: Cleanup Workflow

on:
  schedule:
    - cron: '0 17 * * *'  # Setiap hari pukul 00:00 WIB
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install GitHub CLI
        uses: cli/gh-action@v2

      - name: Install gh-actions-cache extension
        run: gh extension install actions/gh-actions-cache

      - name: Delete all GitHub Actions caches
        run: gh actions-cache delete --all --confirm

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Delete Docker Hub tags except "latest"
        env:
          REPO: ${{ secrets.DOCKERHUB_USERNAME }}/${ secrets.DOCKERHUB_PROJECT }}
        run: |
          echo "Fetching all tags..."
          tags=$(curl -s "https://hub.docker.com/v2/repositories/$REPO/tags?page_size=100" | jq -r '.results[].name')
          for tag in $tags; do
            if [ "$tag" != "latest" ]; then
              echo "Deleting tag: $tag"
              curl -X DELETE \
                -u "${{ secrets.DOCKERHUB_USERNAME }}:${{ secrets.DOCKERHUB_TOKEN }}" \
                "https://hub.docker.com/v2/repositories/$REPO/tags/$tag/"
            fi
          done
