name: 🔥 Cleanup Cache & Docker Images

on:
  workflow_dispatch:  # Manual trigger dari GitHub UI

jobs:
  cleanup:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}  # Token personal GitHub
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      DOCKERHUB_PROJECT: ${{ secrets.DOCKERHUB_PROJECT }}

    steps:
      - name: 🧾 Checkout repository (diperlukan oleh GitHub CLI)
        uses: actions/checkout@v4

      - name: 🔧 Install GitHub CLI
        run: sudo apt-get install -y gh

      - name: 🔌 Install gh-actions-cache extension
        run: gh extension install actions/gh-actions-cache

      - name: 🔐 Authenticate GitHub CLI
        run: echo "$GH_TOKEN" | gh auth login --with-token

      - name: 🧹 Delete all GitHub Actions caches
        run: |
          echo "Menghapus semua cache GitHub Actions..."
          gh actions-cache list -R ${{ github.repository }} | cut -f 1 | while read -r cache_key; do
            echo "🗑️ Menghapus cache: $cache_key"
            gh actions-cache delete "$cache_key" -R ${{ github.repository }} --confirm
          done

      - name: 🔐 Login to Docker Hub
        run: echo "$DOCKERHUB_TOKEN" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin

      - name: 🧹 Delete all Docker Hub tags except 'latest'
        run: |
          echo "Mengambil tag Docker Hub selain 'latest'..."
          REPO="${DOCKERHUB_USERNAME}/${DOCKERHUB_PROJECT}"
          TAGS=$(curl -s -u "${DOCKERHUB_USERNAME}:${DOCKERHUB_TOKEN}" \
            "https://hub.docker.com/v2/repositories/${REPO}/tags?page_size=100" | jq -r '.results[].name')

          for tag in $TAGS; do
            if [ "$tag" != "latest" ]; then
              echo "🗑️ Menghapus tag: $tag"
              curl -s -X DELETE -u "${DOCKERHUB_USERNAME}:${DOCKERHUB_TOKEN}" \
                "https://hub.docker.com/v2/repositories/${REPO}/tags/${tag}/"
            fi
          done
