name: Cleanup

on:
  schedule:
    - cron: '0 17 * * *' # Daily at 00:00 WIB
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Clear GitHub Actions cache
        run: |
          echo "Clearing old caches with proper permissions..."
          
          # Get all caches
          CACHES=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                        -H "Accept: application/vnd.github+json" \
                        -H "X-GitHub-Api-Version: 2022-11-28" \
                        "https://api.github.com/repos/${{ github.repository }}/actions/caches")
          
          # Delete old buildkit caches (keep last 2)
          echo "$CACHES" | jq -r '.actions_caches | map(select(.key | test("buildkit|buildx"))) | .[2:] | .[].id' | while read cache_id; do
            if [ ! -z "$cache_id" ]; then
              echo "Deleting old buildkit cache ID: $cache_id"
              curl -X DELETE \
                   -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                   -H "Accept: application/vnd.github+json" \
                   -H "X-GitHub-Api-Version: 2022-11-28" \
                   "https://api.github.com/repos/${{ github.repository }}/actions/caches/$cache_id" || true
              sleep 0.5
            fi
          done
          
          echo "Cache cleanup completed"

      - name: GHCR cleanup info
        run: |
          echo "📋 GHCR images auto-expire after 30 days if untagged"
          echo "🗑️ Manual cleanup: https://github.com/${{ github.repository }}/pkgs/container/${{ github.event.repository.name }}"
          echo "✨ GHCR provides better integration with GitHub"