name: 🚀 Build & Push Docker Image

on:
  push:  # Build on every commit to any branch
  pull_request:
  workflow_dispatch:  # Manual trigger

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository_owner }}/ambp

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract Git commit short SHA
      id: vars
      run: echo "sha_short=$(git rev-parse --short HEAD)" >> "$GITHUB_OUTPUT"

    - name: Check for changes
      id: changes
      run: |
        if git diff --quiet HEAD~1 HEAD -- Dockerfile requirements.txt app/; then
          echo "changed=false" >> "$GITHUB_OUTPUT"
        else
          echo "changed=true" >> "$GITHUB_OUTPUT"
        fi

    - name: Clear Docker cache on corruption
      if: steps.changes.outputs.changed == 'true'
      run: |
        docker builder prune -f --filter until=1h
        docker system prune -f

    - name: Build and push Docker image (latest and git sha)
      if: steps.changes.outputs.changed == 'true' || github.event_name == 'workflow_dispatch'
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: |
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.vars.outputs.sha_short }}
        labels: |
          org.opencontainers.image.description=Asset Management System
          org.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }}
        cache-from: type=gha,scope=latest
        cache-to: type=gha,mode=max,scope=latest
        no-cache: ${{ github.event_name == 'workflow_dispatch' }}
        platforms: linux/amd64

    - name: Deploy to Render
      if: github.ref == 'refs/heads/main' && (steps.changes.outputs.changed == 'true' || github.event_name == 'workflow_dispatch')
      run: |
        echo "Triggering Render deployment..."
        RESPONSE=$(curl -s -w "\n%{http_code}" -X POST \
          "https://api.render.com/v1/services/${{ secrets.RENDER_SERVICE_ID }}/deploys" \
          -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
          -H "Content-Type: application/json" \
          -d '{}')
        
        HTTP_CODE=$(echo "$RESPONSE" | tail -n1)
        BODY=$(echo "$RESPONSE" | head -n -1)
        
        echo "HTTP Status: $HTTP_CODE"
        echo "Response: $BODY"
        
        if [ "$HTTP_CODE" -eq 200 ] || [ "$HTTP_CODE" -eq 201 ] || [ "$HTTP_CODE" -eq 202 ]; then
          echo "✅ Deployment triggered successfully"
        else
          echo "❌ Deployment failed with status $HTTP_CODE"
          exit 1
        fi

    - name: Build summary
      run: |
        echo "🚀 Build completed successfully"
        echo "📦 Image pushed: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest"
        echo "🏷️ Image pushed: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.vars.outputs.sha_short }}"
        if [ "${{ github.ref }}" == "refs/heads/main" ]; then
          echo "🌐 Render deployment triggered"
        fi

  clean:
    needs: build
    runs-on: ubuntu-latest
    if: always() && github.ref == 'refs/heads/main'
    permissions:
      actions: write
      contents: read
      packages: write
    
    steps:
    - name: Log in to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Clean old images and caches
      run: |
        echo "Cleaning old images and caches..."
        
        # Clean GitHub Actions cache (keep latest)
        CACHES=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                      -H "Accept: application/vnd.github+json" \
                      -H "X-GitHub-Api-Version: 2022-11-28" \
                      "https://api.github.com/repos/${{ github.repository }}/actions/caches")
        
        # Delete old caches but keep 'latest' scope
        echo "$CACHES" | jq -r '.actions_caches | map(select(.key | contains("latest") | not)) | sort_by(.created_at) | reverse | .[2:] | .[].id' | while read cache_id; do
          if [ ! -z "$cache_id" ]; then
            echo "Deleting cache: $cache_id"
            curl -X DELETE \
                 -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                 -H "Accept: application/vnd.github+json" \
                 -H "X-GitHub-Api-Version: 2022-11-28" \
                 "https://api.github.com/repos/${{ github.repository }}/actions/caches/$cache_id" || true
          fi
        done
        
        # Clean old GHCR images (keep latest + last 2 SHA tags)
        echo "Cleaning old GHCR images..."
        
        # Get package versions
        VERSIONS=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                        -H "Accept: application/vnd.github+json" \
                        "https://api.github.com/users/${{ github.repository_owner }}/packages/container/ambp/versions")
        
        # Delete old versions (keep latest + 2 recent)
        echo "$VERSIONS" | jq -r '.[3:] | .[].id' | while read version_id; do
          if [ ! -z "$version_id" ]; then
            echo "Deleting GHCR version: $version_id"
            curl -X DELETE \
                 -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                 -H "Accept: application/vnd.github+json" \
                 "https://api.github.com/users/${{ github.repository_owner }}/packages/container/ambp/versions/$version_id" || true
          fi
        done
        
        echo "Cleanup completed"
