name: 🚀 Build & Push Docker Image

on:
  push:  # Build on every commit to any branch
  pull_request:
  workflow_dispatch:  # Manual trigger

env:
  DOCKERHUB_REPO: ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_PROJECT }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Extract Git commit short SHA
      id: vars
      run: echo "sha_short=$(git rev-parse --short HEAD)" >> "$GITHUB_OUTPUT"

    - name: Build and push Docker image (latest and git sha)
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: |
          ${{ env.DOCKERHUB_REPO }}:latest
          ${{ env.DOCKERHUB_REPO }}:${{ steps.vars.outputs.sha_short }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Deploy to Render
      if: github.ref == 'refs/heads/main'
      run: |
        echo "Triggering Render deployment..."
        RESPONSE=$(curl -s -w "\n%{http_code}" -X POST \
          "https://api.render.com/v1/services/${{ secrets.RENDER_SERVICE_ID }}/deploys" \
          -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
          -H "Content-Type: application/json" \
          -d '{}')
        
        HTTP_CODE=$(echo "$RESPONSE" | tail -n1)
        BODY=$(echo "$RESPONSE" | head -n -1)
        
        echo "HTTP Status: $HTTP_CODE"
        echo "Response: $BODY"
        
        if [ "$HTTP_CODE" -eq 200 ] || [ "$HTTP_CODE" -eq 201 ]; then
          echo "✅ Deployment triggered successfully"
        else
          echo "❌ Deployment failed with status $HTTP_CODE"
          exit 1
        fi

    - name: Build summary
      run: |
        echo "🚀 Build completed successfully"
        echo "📦 Image pushed: ${{ env.DOCKERHUB_REPO }}:latest"
        echo "🏷️ Image pushed: ${{ env.DOCKERHUB_REPO }}:${{ steps.vars.outputs.sha_short }}"
        if [ "${{ github.ref }}" == "refs/heads/main" ]; then
          echo "🌐 Render deployment triggered"
        fi
